[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"
readme = "README.md"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "some_bench.rs"
harness = false
